# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'faceattention.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(801, 480)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 480, 480))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(110, 400, 211, 41))
        self.widget_2.setStyleSheet("background-color: rgba(49, 50, 54, 63);\n"
"border-radius:8px")
        self.widget_2.setObjectName("widget_2")
        self.Tip = QtWidgets.QLabel(self.widget_2)
        self.Tip.setGeometry(QtCore.QRect(0, 0, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Tip.setFont(font)
        self.Tip.setStyleSheet("color: rgb(0, 255, 0);\n"
"background-color: rgb(173, 173, 173);\n"
"font: 20pt \"Arial\";\n"
"border:none;\n"
"border-radius:8px")
        self.Tip.setAlignment(QtCore.Qt.AlignCenter)
        self.Tip.setObjectName("Tip")
        self.widget_2.hide()
        # self.Tip.hide()
        self.VideoLabel = QtWidgets.QLabel(self.widget)
        self.VideoLabel.setGeometry(QtCore.QRect(0, 0, 480, 480))
        self.VideoLabel.setText("")
        self.VideoLabel.setObjectName("VideoLabel")
        # 启用自动缩放
        self.VideoLabel.setScaledContents(True)
        self.VideoLabel.raise_()
        self.widget_2.raise_()
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setGeometry(QtCore.QRect(480, 0, 321, 480))
        self.widget_3.setStyleSheet("QWidget{\n"
"    border:1px solid #313226;\n"
"    border-radius:4px;\n"
"    background-color: rgb(37, 40, 49, 150);\n"
"}\n"
"QWidget#titlelb{\n"
"    \n"
"    font: 25 16pt \"微软雅黑\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QWidget#facelb{\n"
"    \n"
"    border-radius:75\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.titlelb = QtWidgets.QLabel(self.widget_3)
        self.titlelb.setGeometry(QtCore.QRect(10, 10, 301, 41))
        self.titlelb.setAlignment(QtCore.Qt.AlignCenter)
        self.titlelb.setObjectName("titlelb")
        self.facelb = QtWidgets.QLabel(self.widget_3)
        self.facelb.setGeometry(QtCore.QRect(89, 60, 150, 150))
        self.facelb.setText("")
        self.facelb.setAlignment(QtCore.Qt.AlignCenter)
        self.facelb.setObjectName("facelb")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(10, 220, 301, 50))
        self.widget_4.setStyleSheet("border:1px solid #313226;\n"
"border-radius:4px;\n"
"background-color: rgb(37, 40, 49, 150);\n"
"\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 71, 51))
        self.label_5.setStyleSheet("border:none;\n"
"color: rgb(145, 145, 135);\n"
"font: 15pt \"微软雅黑\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit.setGeometry(QtCore.QRect(80, 0, 221, 51))
        self.lineEdit.setStyleSheet("border:none;\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"微软雅黑\";")
        self.lineEdit.setObjectName("lineEdit")
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setGeometry(QtCore.QRect(10, 270, 301, 50))
        self.widget_5.setStyleSheet("QWidget{\n"
"    border:1px solid #313226;\n"
"    border-radius:4px;\n"
"    background-color: rgb(37, 40, 49, 150);\n"
"}\n"
"QWidget:QLabel{\n"
"    border:none;\n"
"    color: rgb(125, 100, 127);\n"
"    font: 18pt \"微软雅黑\";\n"
"}\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.label_6 = QtWidgets.QLabel(self.widget_5)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 71, 51))
        self.label_6.setStyleSheet("border:none;\n"
"color: rgb(145, 145, 135);\n"
"font: 15pt \"微软雅黑\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 0, 221, 51))
        self.lineEdit_2.setStyleSheet("border:none;\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"微软雅黑\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setGeometry(QtCore.QRect(10, 320, 301, 50))
        self.widget_6.setStyleSheet("QWidget{\n"
"    border:1px solid #313226;\n"
"    border-radius:4px;\n"
"    background-color: rgb(37, 40, 49, 150);\n"
"}\n"
"QWidget:QLabel{\n"
"    border:none;\n"
"    color: rgb(125, 100, 127);\n"
"    font: 18pt \"微软雅黑\";\n"
"}\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.label_7 = QtWidgets.QLabel(self.widget_6)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 71, 51))
        self.label_7.setStyleSheet("border:none;\n"
"color: rgb(145, 145, 135);\n"
"font: 15pt \"微软雅黑\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 0, 221, 51))
        self.lineEdit_3.setStyleSheet("border:none;\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"微软雅黑\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.widget_7 = QtWidgets.QWidget(self.widget_3)
        self.widget_7.setGeometry(QtCore.QRect(10, 370, 301, 50))
        self.widget_7.setStyleSheet("QWidget{\n"
"    border:1px solid #313226;\n"
"    border-radius:4px;\n"
"    background-color: rgb(37, 40, 49, 150);\n"
"}\n"
"QWidget:QLabel{\n"
"    border:none;\n"
"    color: rgb(125, 100, 127);\n"
"    font: 18pt \"微软雅黑\";\n"
"}\n"
"")
        self.widget_7.setObjectName("widget_7")
        self.label_8 = QtWidgets.QLabel(self.widget_7)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 71, 51))
        self.label_8.setStyleSheet("border:none;\n"
"color: rgb(145, 145, 135);\n"
"font: 15pt \"微软雅黑\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 0, 221, 51))
        self.lineEdit_4.setStyleSheet("border:none;\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"微软雅黑\";")
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Tip.setText(_translate("Form", "认证成功"))
        self.titlelb.setText(_translate("Form", "人脸识别考勤系统"))
        self.label_5.setText(_translate("Form", "工号"))
        self.lineEdit.setText(_translate("Form", "10001"))
        self.label_6.setText(_translate("Form", "姓名"))
        self.lineEdit_2.setText(_translate("Form", "10001"))
        self.label_7.setText(_translate("Form", "部门"))
        self.lineEdit_3.setText(_translate("Form", "10001"))
        self.label_8.setText(_translate("Form", "时间"))
        self.lineEdit_4.setText(_translate("Form", "10001"))





