# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\passwd.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog

class Ui_Passwd(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.init_ui()

    def init_ui(self):
        self.setObjectName("Dialog")
        self.resize(400, 300)
        # 设置整体背景为雅白色（与主界面风格统一）
        self.setStyleSheet("background-color: rgb(250, 250, 245);")

        # 按钮框样式优化
        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        self.buttonBox.setGeometry(QtCore.QRect(20, 230, 341, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        # 按钮样式设置，与主界面按钮风格匹配
        self.buttonBox.setStyleSheet("""
            QPushButton {
                background-color: transparent;
                color: #333; 
                font: 11pt "微软雅黑"; 
                border: 1px solid #ccc; 
                border-radius: 6px; 
                padding: 8px;
                min-width: 80px;
            }
            QPushButton:hover {
                background-color: rgba(255, 255, 255, 0.5);
            }
        """)

        # 标签样式优化
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(150, 10, 120, 41))
        self.label.setObjectName("label")
        # 标签字体和颜色调整
        self.label.setStyleSheet("""
            color: #666; 
            font: 13pt "微软雅黑"; 
            background-color: transparent;
        """)

        # 密码输入框样式优化
        self.lineEdit = QtWidgets.QLineEdit(self)
        self.lineEdit.setGeometry(QtCore.QRect(90, 50, 211, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        # 输入框使用雅白色背景，与主界面输入框风格统一
        self.lineEdit.setStyleSheet("""
            background-color: rgba(255, 255, 254, 0.8);
            color: #333; 
            border: 1px solid #ddd;
            font: 13pt "微软雅黑"; 
            padding: 8px; 
            border-radius: 6px;
        """)

        self.retranslateUi()
        self.buttonBox.accepted.connect(self.accept)  # type: ignore
        self.buttonBox.rejected.connect(self.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "管理员"))
        self.label.setText(_translate("Dialog", "请输入密码"))